FROM ubuntu:22.04

# Gerekli adımlar
RUN apt-get update && apt-get install -y locales \
    && locale-gen en_US en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
    && export LANG=en_US.UTF-8

RUN apt-get install -y software-properties-common curl gnupg \
    && add-apt-repository universe \
    && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" > /etc/apt/sources.list.d/ros2.list

#ENV DEBIAN_FRONTEND noninteractive
ENV TZ=Europe/Istanbul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y ros-humble-desktop \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# ROS ortamını aktif hale getirme
#ros2 tanınmadı aşağıdaki satırda
#CMD ["bash", "-c", "source /opt/ros/humble/setup.bash && exec bash"]

RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

